# Generated by Django 3.0.7 on 2021-01-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='autogenerated', max_length=100)),
                ('breakfast', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_component_breakfast', to='recipes.Recipe')),
                ('dinner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_component_dinner', to='recipes.Recipe')),
                ('lunch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_component_lunch', to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(choices=[('AIP', 'AIP'), ('NORMAL', 'NORMAL')], default='AIP', max_length=6)),
                ('friday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friday_plan', to='plans.DayPlan')),
                ('monday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monday_plan', to='plans.DayPlan')),
                ('saturday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_plan', to='plans.DayPlan')),
                ('sunday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_plan', to='plans.DayPlan')),
                ('thursday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_plan', to='plans.DayPlan')),
                ('tuesday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_plan', to='plans.DayPlan')),
                ('wednesday', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_plan', to='plans.DayPlan')),
            ],
        ),
    ]
