[tool.poetry]
name = "diet_plan_generator"
version = "0.1.0"
description = ""
authors = ["noemi <n.kowalewska@clearcode.cc>"]

[tool.poetry.dependencies]
python = "^3.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
