# Generated by Django 3.0.7 on 2020-11-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=1000)),
                ('type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('desert', 'desert'), ('snack', 'snack')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('component', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredients')),
                ('receipt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.Receipt')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='components',
            field=models.ManyToManyField(through='recipes.ReceiptComponent', to='ingredients.Ingredients'),
        ),
    ]
