# Generated by Django 3.0.7 on 2020-11-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='diet_name',
            field=models.CharField(choices=[('AIP', 'AIP'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=6),
        ),
    ]
