# Generated by Django 3.0.7 on 2020-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_receipt_diet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcomponent',
            name='measurement',
            field=models.CharField(choices=[('small spoon', 'small spoon'), ('big spoon', 'big spoon'), ('grams', 'grams'), ('kilograms', 'kilograms'), ('items', 'items'), ('slices', 'slices')], default='grams', max_length=11),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='diet_name',
            field=models.CharField(choices=[('AIP', 'AIP'), ('NORMAL', 'NORMAL')], default='AIP', max_length=6),
        ),
    ]
