# Generated by Django 3.0.7 on 2020-11-25 20:39

from django.db import migrations
from django.core.management import call_command

def forwards_func(apps, schema_editor):
    call_command('data_loader', file_path='recipes/management/commands/coctails.json', verbosity=2)



def reverse_func(apps, schema_editor):
    print('reverse')


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201125_2036'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, elidable=False)
    ]
