# Generated by Django 3.0.7 on 2020-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201129_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dessert', 'dessert'), ('snack', 'snack'), ('addition', 'addition')], max_length=9),
        ),
        migrations.AlterField(
            model_name='receiptcomponent',
            name='measurement',
            field=models.CharField(choices=[('small spoon', 'small spoon'), ('big spoon', 'big spoon'), ('grams', 'grams'), ('kilograms', 'kilograms'), ('items', 'items'), ('slices', 'slices'), ('glasses', 'glasses'), ('cm', 'cm'), ('can', 'can'), ('ml', 'ml'), ('bunch', 'bunch')], default='grams', max_length=11),
        ),
    ]
