# Generated by Django 3.0.7 on 2020-12-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Fat',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Starch',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.CreateModel(
            name='Cabbage',
            fields=[
                ('vegetable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Vegetable')),
            ],
            bases=('ingredients.vegetable',),
        ),
        migrations.CreateModel(
            name='GreenVegetable',
            fields=[
                ('vegetable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Vegetable')),
            ],
            bases=('ingredients.vegetable',),
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('protein_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Protein')),
            ],
            bases=('ingredients.protein',),
        ),
        migrations.CreateModel(
            name='Pickled',
            fields=[
                ('vegetable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Vegetable')),
            ],
            bases=('ingredients.vegetable',),
        ),
        migrations.CreateModel(
            name='ProteinFruit',
            fields=[
                ('protein_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Protein')),
            ],
            bases=('ingredients.protein',),
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
        migrations.CreateModel(
            name='RedMeat',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
    ]
