# Generated by Django 3.0.7 on 2021-01-05 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetable', 'vegetable'), ('spices', 'spices'), ('protein', 'protein'), ('meat', 'meat'), ('fat', 'fat'), ('fruit', 'fruit'), ('liquid', 'liquid'), ('starch', 'starch'), ('green_vegetable', 'green_vegetable'), ('cabbage', 'lunch'), ('fish', 'dessert'), ('poultry', 'poultry'), ('red_meat', 'red_meat'), ('protein_fruit', 'protein_fruit'), ('unknown', 'unknown')], default='unknown', max_length=100), size=None),
        ),
    ]
