# Generated by Django 3.0.7 on 2020-11-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
        migrations.CreateModel(
            name='ProteinFruit',
            fields=[
                ('protein_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Protein')),
            ],
            bases=('ingredients.protein',),
        ),
        migrations.CreateModel(
            name='RedMeat',
            fields=[
                ('meat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Meat')),
            ],
            bases=('ingredients.meat',),
        ),
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
        migrations.RemoveField(
            model_name='meat',
            name='type',
        ),
    ]
