# Generated by Django 3.0.7 on 2020-12-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20201125_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('ingredients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.Ingredients')),
            ],
            bases=('ingredients.ingredients',),
        ),
    ]
