name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Create .netrc for Heroku Auth"
      shell: bash
      run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          EOF`
      env:
          EMAIL: noemikow8@gmail.com
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
    - name: "Add remote"
      shell: "bash"
      run: |
          heroku git:remote --app vast-bastion-73673
    - name: "Push to heroku"
      shell: "bash"
      run: |
          git push heroku HEAD:master
      env: 
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    - name: Release
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:release -a vast-bastion-73673 web 
